name: Build and Push to GitHub Container Registry

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # 🚨 necesario para publicar en GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get commit hash
        id: commit_hash
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Get version from package.json
        id: version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/simple-rest-api:${{ env.VERSION }}-${{ env.COMMIT_HASH }}
          IMAGE_NAME_LATEST=${{IMAGE_NAME}}:latest
          IMAGE_NAME_VERSION=${{IMAGE_NAME}}:v${{ env.VERSION }}-${{ env.COMMIT_HASH }}
          docker build -t $IMAGE_NAME .
          docker tag $IMAGE_NAME $IMAGE_NAME_LATEST
          docker tag $IMAGE_NAME $IMAGE_NAME_VERSION
          echo "IMAGE_NAME_LATEST=$IMAGE_NAME_LATEST" >> $GITHUB_ENV
          echo "IMAGE_NAME_VERSION=$IMAGE_NAME_VERSION" >> $GITHUB_ENV

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME_LATEST
          docker push $IMAGE_NAME_VERSION
